# muvm-steam-fixes -- Steam under muvm on Apple Silicon
#
#   1. muvm-dmabuf-fixup.so  GPU acceleration (dma-buf / KVM EFAULT)
#   2. muvm-guest-dbus.sh    system D-Bus in the guest ("Waiting for network")
#
#   make            build the library
#   make install    install both, plus Steam wrapper and .desktop entry
#   make uninstall  remove them again
#   make check      self-test: run muvm and report the guest's GL renderer
#   make clean      remove build artifacts
#
# Everything installs under $(PREFIX), by default into the user's home.
# No system packages are touched.

TARGET  := muvm-dmabuf-fixup.so
SRC     := muvm-dmabuf-fixup.c
DBUSSH  := muvm-guest-dbus.sh

PREFIX  ?= $(HOME)/.local
LIBDIR  ?= $(PREFIX)/lib
BINDIR  ?= $(PREFIX)/bin
APPDIR  ?= $(PREFIX)/share/applications

CC      ?= gcc
CFLAGS  ?= -O2 -Wall -Wextra
CFLAGS  += -fPIC
LDFLAGS += -shared
LDLIBS  += -ldl

SYSTEM_STEAM    := /usr/bin/steam-aarch64
SYSTEM_DESKTOP  := /usr/share/applications/steam.desktop
WRAPPER         := $(BINDIR)/steam-aarch64
DESKTOP         := $(APPDIR)/steam.desktop

.PHONY: all install uninstall check clean

all: $(TARGET)

$(TARGET): $(SRC)
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $< $(LDLIBS)

install: $(TARGET)
	@# A running VM has the library mapped; overwriting it would pull the
	@# mapping out from under it. muvm renames itself to "libkrun VM".
	@if ps -eo comm= | grep -q 'libkrun'; then \
	    echo "Aborted: a muvm VM is running (Steam?)."; \
	    echo "Close it first -- the library is mapped in that process."; \
	    exit 1; \
	fi
	install -d $(LIBDIR) $(BINDIR)
	install -m 0755 $(TARGET) $(LIBDIR)/$(TARGET)
	@echo "==> $(LIBDIR)/$(TARGET)"
	install -m 0755 $(DBUSSH) $(LIBDIR)/$(DBUSSH)
	@echo "==> $(LIBDIR)/$(DBUSSH)"
	@# steam-aarch64 hardcodes its muvm invocation and forwards trailing
	@# arguments to Steam, so -x would never reach muvm. Call muvm directly.
	@printf '%s\n' \
	    '#!/bin/sh' \
	    '# Generated by muvm-steam-fixes (make install). Remove: make uninstall' \
	    'FIXUP=$(LIBDIR)/$(TARGET)' \
	    'DBUS=$(LIBDIR)/$(DBUSSH)' \
	    '[ -e "$$FIXUP" ] && export LD_PRELOAD="$${FIXUP}$${LD_PRELOAD:+:$$LD_PRELOAD}"' \
	    'if [ -x "$$DBUS" ] && [ -x /usr/bin/steam-muvm ]; then' \
	    '    exec muvm -x "$$DBUS" /usr/bin/steam-muvm "$$@"' \
	    'else' \
	    '    exec $(SYSTEM_STEAM) "$$@"' \
	    'fi' \
	    > $(WRAPPER)
	@chmod 0755 $(WRAPPER)
	@echo "==> $(WRAPPER)"
	@# The system .desktop calls steam-aarch64 by absolute path and would
	@# bypass the wrapper in PATH, so install a local copy pointing at it.
	@if [ -e $(SYSTEM_DESKTOP) ]; then \
	    install -d $(APPDIR); \
	    sed 's|^Exec=$(SYSTEM_STEAM)|Exec=$(WRAPPER)|' $(SYSTEM_DESKTOP) > $(DESKTOP); \
	    echo "==> $(DESKTOP)"; \
	else \
	    echo "!!  $(SYSTEM_DESKTOP) not found -- skipping .desktop"; \
	fi
	@echo
	@echo "Done. Start Steam as usual; $(BINDIR) must precede /usr/bin in PATH:"
	@command -v steam-aarch64 || true

uninstall:
	rm -f $(LIBDIR)/$(TARGET) $(LIBDIR)/$(DBUSSH) $(WRAPPER) $(DESKTOP)
	@echo "Removed: $(LIBDIR)/$(TARGET), $(LIBDIR)/$(DBUSSH), $(WRAPPER), $(DESKTOP)"

# Uses surfaceless eglinfo so no X display is required.
check: $(TARGET)
	@tmp=$$(mktemp -d); \
	printf '%s\n' '#!/bin/bash' \
	    "exec >$$tmp/out.txt 2>&1" \
	    'unset DISPLAY WAYLAND_DISPLAY XAUTHORITY' \
	    'EGL_PLATFORM=surfaceless timeout 60 eglinfo' > $$tmp/probe.sh; \
	chmod +x $$tmp/probe.sh; \
	echo "Running muvm (default gpu-mode is drm) ..."; \
	LD_PRELOAD=$(CURDIR)/$(TARGET) timeout 240 muvm $$tmp/probe.sh >$$tmp/host.txt 2>&1; \
	echo "muvm exit=$$?"; \
	if grep -q 'Bad address' $$tmp/host.txt; then \
	    echo "FAILED: EFAULT still occurs."; rm -rf $$tmp; exit 1; \
	fi; \
	if ! grep -q 'OpenGL core profile renderer' $$tmp/out.txt; then \
	    echo "FAILED: no renderer reported."; rm -rf $$tmp; exit 1; \
	fi; \
	hw=$$(grep 'OpenGL core profile renderer' $$tmp/out.txt \
	      | grep -vE 'llvmpipe|softpipe|swrast' | head -1); \
	if [ -z "$$hw" ]; then \
	    echo "FAILED: software renderers only:"; \
	    grep 'OpenGL core profile renderer' $$tmp/out.txt | sort -u; \
	    rm -rf $$tmp; exit 1; \
	fi; \
	echo "$$hw"; \
	echo "OK -- GPU acceleration active."; rm -rf $$tmp

clean:
	rm -f $(TARGET)
